/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Stitch "Surgical Precision Retailer" semantic tokens ──
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#ffffff",
        "surface": "#fbf9f9",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#e9e8e7",
        "surface-container-highest": "#e3e2e2",
        "surface-dim": "#dadada",
        "surface-variant": "#e3e2e2",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#303031",
        "inverse-on-surface": "#f2f0f0",
        "outline": "#e4e4e7",
        "outline-variant": "#e4e4e7",
        "primary": "#000000",
        "primary-container": "#1b1b1b",
        "on-primary": "#ffffff",
        "on-primary-container": "#848484",
        "secondary": "#5d5f5f",
        "secondary-container": "#dfe0e0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#616363",
        "tertiary": "#000000",
        "tertiary-container": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#ffffff",
        "on-background": "#1b1c1c",
        "surface-tint": "#5e5e5e",
        "inverse-primary": "#c6c6c6",
        // ── Accent colors ──
        "accent-green": "#16A34A",
        "accent-blue": "#2563EB",
        "accent-amber": "#D97706",
        "accent-red": "#DC2626",
        // ── Legacy aliases (so existing component code still works) ──
        background: "var(--background)",
        foreground: "var(--foreground)",
        bgPrimary: "#ffffff",
        bgSecondary: "#ffffff",
        bgTertiary: "#f4f4f5",
        borderDefault: "#e4e4e7",
        borderHover: "#09090b",
        textPrimary: "#09090b",
        textSecondary: "#71717a",
        textMuted: "#a1a1aa",
        accentGreen: "#16A34A",
        accentGreenLight: "#f0fdf4",
        accentBlue: "#2563EB",
        accentBlueLight: "#eff6ff",
        accentAmber: "#D97706",
        accentAmberLight: "#fffbeb",
        accentRed: "#DC2626",
        accentRedLight: "#fef2f2",
        // (legacy purple kept for any stray references)
        primaryContainer: "#1b1b1b",
        secondary_old: "#71717a",
        secondaryContainer: "#e1e1e1",
      },
      fontFamily: {
        sans: ["var(--font-dm-sans)", "DM Sans", "sans-serif"],
        serif: ["var(--font-instrument-serif)", "Instrument Serif", "serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        // Stitch-named families
        "display-hero": ["var(--font-dm-sans)", "sans-serif"],
        "display-hero-accent": ["var(--font-instrument-serif)", "serif"],
        "headline-lg": ["var(--font-dm-sans)", "sans-serif"],
        "headline-md": ["var(--font-dm-sans)", "sans-serif"],
        "body-lg": ["var(--font-dm-sans)", "sans-serif"],
        "body-sm": ["var(--font-dm-sans)", "sans-serif"],
        "metric-label": ["var(--font-dm-sans)", "sans-serif"],
        "price-display": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-hero": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-accent": ["52px", { lineHeight: "1.1", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "metric-label": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "price-display": ["18px", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "scale-xs": "4px",
        "scale-sm": "8px",
        "scale-md": "16px",
        "scale-lg": "24px",
        "scale-xl": "48px",
        "navbar_height": "64px",
        "container_max_width": "1280px",
        "gutter": "24px",
      },
      boxShadow: {
        card: "0 4px 24px rgba(0,0,0,0.06)",
        hover: "0 8px 40px rgba(0,0,0,0.10)",
        sm: "0 1px 3px rgba(0,0,0,0.06)",
      },
      maxWidth: {
        "container_max_width": "1280px",
      },
    },
  },
  plugins: [],
};
